# Generated by Django 2.2.6 on 2019-10-07 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapp', '0002_auto_20191004_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytype',
            options={'verbose_name': 'categorytype', 'verbose_name_plural': 'categorytypes'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
