# Generated by Django 2.2.6 on 2019-10-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapp', '0002_auto_20191010_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='line_items',
            field=models.ManyToManyField(through='bangazonapp.OrderProduct', to='bangazonapp.Product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bangazonapp.Order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='bangazonapp.Product'),
        ),
    ]
